module.exports = {
    STORE_KEY: 'a56z0fzrNpl^2',
    screen :'',
    time : 0,
    BASE_URL: 'http://139.59.76.223/anytimedoc/api/',
    home :'home',
    Signin :'Signin',
    Signup :'Signup',
    guid:'',
    muid:'',
    module:'',
    youtubekey:'AIzaSyCkk0Mc6Hha2LUn3NHubv0LLSiumoPVhWs',
    is_yt:0,
    equipment:[],
    newsWhich:'',
    low:0,
    high:0,
    appply : 0,
    onlinetype:'',
    department:'',
    referral:'',
    newsImage:'',
    newsTitle:'',
    front_main :'front_main',
    industry :'',
    categoryID : '',
    array :[],
    userID:'1',
    profile :'',
    rentPurchase:'',
    location:'',
    doctor_condition:'online',
    token: '',
    productname : '',
    username: '',
    gender: '',
    email: '',
    password: '',
    otps: '',
    nurse :'',
    lab:[],
    labid:'',
    bookingflag:'',
    bookingid:'',
    mybookingid:'',
    another:'',
    anothername:'',
    bookingstatus:'',
    chatstatus:'',


    nurseArray:[],
    serviceid :'',
    dob: '',
    lat:'28.70937000',
    long:'77.12312000',
appointmentArray :[],
    speciality :'',
    surgries:[],
    illness:[],
    allergies:[],
    selectedAddress:[],
    date:'',
    time:'',
    equipmentfor:'',
    labdetail:[],
    type:'',
    problem:'',
    searchSpeciality:'',
    medicalEquipment:[],
    shipTime:'',
    imagePath:'',




    related:'',
    productid: '',
    cartId :'',
    myid :'',
    video:'',
    newsid :'',
    derive_category :'derive_category',
    derive_detail_category : 'derive_detail_category',
    info_number :'',
    info_email : '',
    mainid : '',
    user_id:'6',
    anotherid:'66',
    mystatus:'Offline',
    dervie_detail_of_product : 'dervie_detail_of_product',
    userInfo :[],
    myname :'',
    mymobile :'',
    mymember:[],
    price:'',
    referal :'',
    deviceToken:'',
    apply_to:'',
    groupName :'',
    groupId :'',
    groupImage:'',
    profileImage:'',
    editGroup:'',
    myemail :'',
    myusername:'',
    mymobile :'',
    is_refer_verify:'',
   referral_code :'',
    voip:'',

    mypassword :'',
    mydeviceID :'',
    mydeviceType :'',
    mydeviceToken :'',
    mymodel_name :'',
    mycarrier_name :'',
    mydevice_country :'',
    mydevice_memory :'',
    otps :'',
    fmobile :'',
    isScreen :'',
    isScreen :'',
    type :'',
    keyword:'',
    author_id :'',
    author :'',
    comment_id:'',
    post_id:'',
    wallets:'',
    anotherUsername:'',
    commentFlagId:'',
    need_help:'need_help',
    onlinename:'',
    onlinegender:'',
    onlinedob:'',
    onlineaddress:'',
    onlinearea:'',
    onlinecity:'',
    onlineMember:[],
    hid:'',
    bookingtype:'',
    mytypes:'',
    listofimages:"",
    hids:'',
    COLOR: {
        ORANGE: '#C50',
        DARKBLUE: '#0F3274',
        LIGHTBLUE: '#6EA8DA',
        DARKGRAY: '#999',
    },
};